# permissions for end users to view usages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: usage-viewer-role
rules:
- apiGroups:
  - cloud.cmft.com
  resources:
  - usages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.cmft.com
  resources:
  - usages/status
  verbs:
  - get
